import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import {ColorSchemeScript, MantineProvider, mantineHtmlProps, createTheme} from '@mantine/core';

import "./globals.css";
import '@mantine/core/styles.css';

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Pikt 2.0",
    description: "Generated by create next app",
};

const theme = createTheme({
    primaryColor: 'violet'
})

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en" {...mantineHtmlProps}>
            <head>
                <ColorSchemeScript />
            </head>
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                <MantineProvider theme={theme}>
                    {children}
                </MantineProvider>
            </body>
        </html>
    );
}
